server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: full-report-service

  datasource:
    url: jdbc:mysql://localhost:3306/full_report_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Xse1,lo0
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full

resilience4j:
  retry:
    instances:
      full-report-service:
        max-attempts: 3
        wait-duration: 300ms
  circuitbreaker:
    instances:
      full-report-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    br.com.getnet: DEBUG
    org.springframework.cloud.openfeign: DEBUG

services:
  report-gateway-url: http://report-gateway-service:8080
  basic-report-url: http://basic-report-service:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  paths-to-match: "/api/**"
  show-actuator: true
