server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: report-gateway-service

  datasource:
    url: jdbc:postgresql://localhost:5432/report_db
    username: postgres
    password: passw@rd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full

resilience4j:
  circuitbreaker:
    instances:
      basic-report-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10
      full-report-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10

  retry:
    instances:
      basic-report-service:
        max-attempts: 3
        wait-duration: 300ms
      full-report-service:
        max-attempts: 3
        wait-duration: 300ms

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    br.com.getnet: DEBUG
    org.springframework.cloud.openfeign: DEBUG

services:
  basic-report-url: http://basic-report-service:8081
  full-report-url: http://full-report-service:8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  paths-to-match: "/api/**"
  show-actuator: true
